#DNDCSE Config File
#License: Private

#地图名称，仅对计分板有影响
map: 'The Map'
#游戏世界名称
world: 'world'
#最大人数
max: 8
#最小人数
min: 3
#开始时间
wait_time: 60
#大厅位置
lobby:
  x: 0
  y: 64
  z: 0
#游戏开始时的位置
spawn:
  x: 0
  y: 64
  z: 0